### PR TITLE
Fix typeo, "verison" to "version". =)

### PR DESCRIPTION
**Pull request by juan-morales**
Simple silly PR from my side.

### CODE REVIEW

**Comment by juan-morales** [comment]
@googlebot I signed it!

**Comment by bramp** [comment]
Awesome, I noticed I also made this typo in the README. Do you mind fixing it everywhere?

**Comment by juan-morales** [comment]
@bramp Hello. Yes I Will take a look everywhere

**Comment by juan-morales** [comment]
The README fix is the original change of this PR. I looked for More ocurrences of "verison" But... This was the only One. 

If you wish I can Enrich this PR by:
1. Fix the mistaques in the PHP Doc blocks
2. Fix any other typeO in the project


Or


I can keep the PR as It is. 

Your call @bramp 😃

**Comment by bramp** [comment]
Ah sorry, I didn't look closely enough at where the fix was... But LGTM. Thanks for this, future mistaques and typeO can be in a future PR.

**Comment by juan-morales** [comment]
No problem @bramp . Then ok. I leave this PR as It is and will prepare another one for a other fixes.

By the way... How did you learn to write php extensions?

**Comment by bramp** [comment]
As for "How did you learn to write php extensions?" I've written a few over the years, but TBH I basically just copy and paste other examples. I'm not sure I know how to write one :)

**Pull request merged**
